server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  zipkin:
    baseUrl: http://localhost:9411/
  application:
    name: api-catalog
  data:
    mongodb:
      host: localhost
      database: catalog
      port: 27017
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        failureRateThreshold: '40'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        allowHealthIndicatorToFail: 'false'
        registerHealthIndicator: 'true'
        slidingWindowSize: '10'
        permittedNumberOfCallsInHalfOpenState: '3'
        waitDurationInOpenState: '15000'
    instances:
      movies:
        baseConfig: default
      series:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: '3'
        waitDuration: '1000'
        retryExceptions[0]: feign.FeignException$InternalServerError
    instances:
      movies:
        baseConfig: default
      series:
        baseConfig: default
