server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:    
    gateway:      
      discovery:
        locator:
          enabled: true
      routes:
        - id: accountRoute
          uri: http://localhost:8080/
          predicates:
            - Path=/auth/**
        - id: mscatalog
          uri: lb://api-catalog
          predicates:
            - Path=/api/v1/catalog/**
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 170735827649-158cmruordmce5t320jrk477lh9cl3pq.apps.googleusercontent.com
            client-secret: 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
            scope: openid
            redirect_uri: http://localhost:8080/login/oauth2/code/google
        
info:
  app:
    name: ${spring.application.name}

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: true
      serviceURL:
         defaultZone: http://localhost:8761/eureka
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway
